import io

import pytest
from PIL import Image

from palubicki.geom._textures import (
    _PROC_TEXTURES,
    birch_bark_png,
    birch_leaf_png,
    default_leaf_png,
    oak_bark_png,
    oak_leaf_png,
    pine_bark_png,
    pine_needle_png,
)

BARK_GENS = [oak_bark_png, pine_bark_png, birch_bark_png]
LEAF_GENS = [oak_leaf_png, pine_needle_png, birch_leaf_png]


@pytest.mark.parametrize("gen", BARK_GENS)
def test_bark_png_produces_valid_image(gen):
    png = gen(256)
    assert len(png) > 100
    img = Image.open(io.BytesIO(png))
    assert img.size == (256, 256)
    assert img.mode in {"RGB", "RGBA"}


@pytest.mark.parametrize("gen", LEAF_GENS)
def test_leaf_png_is_rgba_with_alpha(gen):
    png = gen(128)
    img = Image.open(io.BytesIO(png))
    assert img.size == (128, 128)
    assert img.mode == "RGBA"
    alpha = img.split()[-1]
    extrema = alpha.getextrema()
    assert extrema[0] == 0, "leaf should have transparent regions outside the silhouette"
    assert extrema[1] == 255, "leaf should have fully opaque pixels inside the silhouette"


@pytest.mark.parametrize("gen", BARK_GENS + LEAF_GENS + [default_leaf_png])
def test_texture_is_deterministic(gen):
    """Same generator in the same process returns identical bytes."""
    a = gen(64)
    b = gen(64)
    assert a == b


@pytest.mark.parametrize("name", sorted(_PROC_TEXTURES.keys()))
def test_texture_cross_process_stable(name):
    """The generator must produce identical bytes regardless of PYTHONHASHSEED.
    Run the same generator under two different seeds, compare outputs."""
    import subprocess
    import sys

    code = (
        "from palubicki.geom._textures import _PROC_TEXTURES; "
        "import sys; "
        f"sys.stdout.buffer.write(_PROC_TEXTURES[{name!r}](64)[:64])"
    )
    out_a = subprocess.run(
        [sys.executable, "-c", code],
        capture_output=True, check=True,
        env={"PYTHONHASHSEED": "0", "PATH": ""},
    ).stdout
    out_b = subprocess.run(
        [sys.executable, "-c", code],
        capture_output=True, check=True,
        env={"PYTHONHASHSEED": "random", "PATH": ""},
    ).stdout
    assert out_a == out_b, f"{name}: bytes differ across PYTHONHASHSEED — hash-randomization leak"


def test_print_current_texture_hashes(capsys):
    """Helper to extract the pin values after a deliberate algorithm change.
    Skipped unless PRINT_TEXTURE_HASHES=1 is set in the env."""
    import hashlib
    import os
    if os.environ.get("PRINT_TEXTURE_HASHES") != "1":
        pytest.skip("set PRINT_TEXTURE_HASHES=1 to print")
    for name in sorted(_PROC_TEXTURES):
        png = _PROC_TEXTURES[name](64)
        sha = hashlib.sha256(png[:64]).hexdigest()
        print(f'    "{name}": "{sha}",')


_TEXTURE_FIRST64_SHA256 = {
    # Generated by test_print_current_texture_hashes; update only on intentional algorithm changes.
    "birch_bark": "5ec0a026eb76828298ee9c51cd7bc3c2617187bfbde15c3483ace050496d3ee4",
    "birch_leaf": "551dbaa516419f2f6f5a99997bfc100a6b5772b15a551cb35ac9bf3d1b36e6b9",
    "oak_bark": "4729a4881141b509c9ebdb9ef631952cb268509b63568edf3d08725b034c8256",
    "oak_leaf": "95acd2c08d93ddab5163caa17abf6b1f5562a070750b9f4783a91e62641dc722",
    "pine_bark": "3af3a4a56c32382e2d521945b28f6aef9e53675ed79331b8752daed3787d4298",
    "pine_needle": "a7d115e79aef443fffede43c5324d6e67b28bfc707150e6ddd1aba0629e64d3e",
}


@pytest.mark.pinned
@pytest.mark.parametrize("name", sorted(_PROC_TEXTURES.keys()))
def test_texture_pinned_hash(name):
    """SHA-256 of the first 64 bytes of each generator's 64-px PNG is pinned.
    Updating these requires deliberate algorithm changes — protects against silent drift."""
    import hashlib
    png = _PROC_TEXTURES[name](64)
    actual = hashlib.sha256(png[:64]).hexdigest()
    assert actual == _TEXTURE_FIRST64_SHA256[name], (
        f"{name}: pin drift\nexpected: {_TEXTURE_FIRST64_SHA256[name]}\nactual:   {actual}"
    )


def test_proc_textures_registry_has_six_entries():
    assert set(_PROC_TEXTURES) == {
        "oak_bark", "pine_bark", "birch_bark",
        "oak_leaf", "pine_needle", "birch_leaf",
    }


def test_proc_textures_callable_returns_bytes():
    for name, gen in _PROC_TEXTURES.items():
        png = gen()
        assert isinstance(png, bytes) and len(png) > 100, f"generator {name} broken"
